coverage:
  range: 70..100
  round: down
  precision: 1
  status:
    project:
      default:
        target: 90%
        threshold: .5%

ignore:
  - "deptry/cli.py"
  - "deptry/core.py"
  - "deptry/utils.py"
