coverage:
  range: 70..100
  round: down
  precision: 1
ignore:
  - "deptry/cli.py"
  - "deptry/core.py"
  - "deptry/utils.py"
  status:
    project:
      default:
        target: auto
        threshold: 0%