site_name: deptry
repo_url: https://github.com/fpgmaas/deptry
site_url: https://fpgmaas.github.io/deptry
site_description: A repository to check for unused dependencies in a poetry managed python project
site_author: Florian Maas

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
            setup_commands:
                - import sys
                - sys.path.append('../')
copyright: Maintained by Florian Maas.
theme:
  name: material
  feature:
    tabs: true
  palette:
    primary: white
    accent: blue
markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true