site_name: deptry
edit_uri: edit/main/docs/
repo_name: fpgmaas/deptry
repo_url: https://github.com/fpgmaas/deptry
site_url: https://fpgmaas.github.io/deptry
site_description: A command line tool to check for unused dependencies in a poetry managed python project.
site_author: Florian Maas
copyright: Maintained by <a href="https://fpgmaas.com">Florian</a>.

nav:
  - Home: index.md
  - Usage and Configuration: usage.md
  - Rules and Violations: rules-violations.md
  - Changelog: CHANGELOG.md
  - Contributing: contributing.md

plugins:
  - search

theme:
  name: material
  features:
    - content.action.edit
    - content.code.copy
    - navigation.footer
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: cyan
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: cyan
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/fpgmaas/deptry
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/deptry/

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
