name: 'Setup Python and Rust Environment'
description: 'Set up Python and Rust for PDM projects with matrix support'
inputs:
  python-version:
    description: 'Python version for setup-python'
    required: true
    default: 3.11
  target:
    description: 'Target architecture for maturin'
    required: true
    default: 'x86_64'

runs:
  using: 'composite'
  steps:

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install PDM and dependencies
      run: |
        python -m pip install pdm
        python -m venv .venv
        source ${{ github.action_path }}/scripts/activate-venv.sh
        python -m pip install --upgrade pip
        pdm config python.use_venv true
        pdm install
      shell: bash

    - name: Setup Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: 1.75.0

    - name: Build and install the project using Maturin
      uses: PyO3/maturin-action@v1
      with:
        target: ${{ inputs.target }}
        command: develop
        sccache: 'true'
