name: 'Setup Python Environment'
description: 'Set up Python environment for the given Python version'

inputs:
  python-version:
    description: 'Python version for setup-python'
    required: true
    default: '3.12'
  build-project:
    description: 'Whether to build the project itself'
    required: true
    default: 'false'

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install uv
      run: pipx install uv
      env:
        # renovate: datasource=pypi depName=uv
        UV_VERSION: '0.4.1'
      shell: bash

    - name: Install Python dependencies
      run: uv sync --frozen ${{ inputs.build-project == 'false' && '--no-install-project' || '' }}
      shell: bash
