name: 'Setup Python and Rust Environment'
description: 'Set up Python and Rust environment for PDM projects with matrix support'

inputs:
  python-version:
    description: 'Python version for setup-python'
    required: true
    default: '3.12'
  target:
    description: 'Target architecture for maturin'
    required: true
    default: 'x86_64'

runs:
  using: 'composite'
  steps:
    - name: Install PDM
      uses: pdm-project/setup-pdm@v4
      env:
        # renovate: datasource=pypi depName=pdm
        PDM_VERSION: "2.17.3"
      with:
        version: ${{ env.PDM_VERSION }}
        python-version: ${{ inputs.python-version }}
        cache: true

    - name: Setup Rust toolchain
      run: rustup component add cargo clippy rustfmt
      shell: bash

    - name: Install Python dependencies
      run: pdm install --frozen-lockfile --no-editable --no-self
      env:
        PDM_VENV_WITH_PIP: "true"
      shell: bash

    - name: Build and install the project using Maturin
      uses: PyO3/maturin-action@v1
      with:
        target: ${{ inputs.target }}
        command: develop
        sccache: 'true'
