site_name: deptry
repo_url: https://github.com/fpgmaas/deptry
site_url: https://fpgmaas.github.io/deptry
site_description: A command line tool to check for unused dependencies in a poetry managed python project.
site_author: Florian Maas

nav:
  - Home: index.md
  - Usage and Configuration: usage.md
  - Configuration with pyproject.toml: pyproject-toml.md
  - FAQ: faq.md
plugins:
  - search
copyright: Maintained by <a href="https://fpgmaas.com">Florian</a>.
theme:
  name: material
  feature:
    tabs: true
  palette:
    primary: white
    accent: blue
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
