on:
    pull_request:
        types: [opened, synchronize, reopened]

name: on-pull-request

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:

      - name: Check out
        uses: actions/checkout@v2

      - name: Set up the environment
        uses: ./.github/actions/setup-poetry-env
        with:
          documentation: false

      - name: Run checks
        uses: ./.github/actions/run-checks

  documentation:
    runs-on: ubuntu-latest
    needs: quality
    steps:

      - name: Check out
        uses: actions/checkout@v2

      - name: Set up the environment
        uses: ./.github/actions/setup-poetry-env
        with:
          documentation: true
        
      - name: Generate documentation
        run: |
            source .venv/bin/activate
            mkdocs gh-deploy --force